# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

singleKmeansC <- function(x, centers) {
    .Call('_packageKmeans_singleKmeansC', PACKAGE = 'packageKmeans', x, centers)
}

